version: "3.9"
services:
  backend:
    build:
      context: ./AI
    container_name: ui-aic-backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5001
      - FLASK_DEBUG=false

  frontend:
    build:
      context: ./front-end/ui-aic
      args:
        NEXT_PUBLIC_FLASK_BASE_URL: http://backend:5001
    container_name: ui-aic-frontend
    environment:
      - FLASK_API_URL=http://backend:5001
      - NEXT_PUBLIC_FLASK_BASE_URL=http://backend:5001
    ports:
      - "3000:3000"
    depends_on:
      - backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ui-aic-cloudflared
    depends_on:
      - frontend
      - backend
    # No config.yml; uses a named tunnel token you'll provide at runtime
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
