services:
  ai-backend:
    build:
      context: ./AI
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./AI:/app
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - HOST=0.0.0.0
      - PORT=5000
      - DEFAULT_VIDEO=pasar
      - DEFAULT_TARGET=Fajar
    networks:
      - ui-aic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./front-end/ui-aic
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_AI_BACKEND_URL=http://localhost:5001
    depends_on:
      ai-backend:
        condition: service_healthy
    networks:
      - ui-aic-network
    restart: unless-stopped

networks:
  ui-aic-network:
    driver: bridge

volumes:
  ai-models:
    driver: local
